### ISSUE TITLE
Swipey Voting/Reply motion needs damping

### ISSUE THREAD

**Issue by Guy-Dudeman** [mlemgroup/mlem#121] opened 2023-06-23 18:10 UTC
## Introduction
When you drag a post or comment to vote on it or reply to it, when you lift your finger after dragging, it just snaps back with no ease-in to the original position. It needs some damping to make it settle more smoothly.

## Requirements
I have no idea how to code this. 

## Discussion
You can look at how Apollo did it, which I feel was perfect, or you can see how they do it in Memmy, but I feel like theirs is a bit too slow settling.

## What I Need
Someone who knows what they're doing with this stuff, to program in some easing into the swipey voting motion.

**Comment by EricBAndrews** [comment] 2023-07-06 00:26
Duplicate of #96

**Closed by EricBAndrews** 2023-07-06 00:26 UTC
Labels: enhancement
