### ISSUE TITLE
Right swipe back to feed

### ISSUE THREAD

**Issue by daveb92** [mlemgroup/mlem#79] opened 2023-06-30 11:55 UTC
## Introduction
Brief history
Left swipe brings you back to feed from post, further left edge swipe brings you back to the communities page, but you can’t right swipe to go back to the feed

## Requirements
What needs to be done?
similar to the left swipe action to go back, have the right swipe go forward

## Discussion
Go more in depth about the proposal
current workaround is going back to the whole feed and starting over / reloading, would be good to take to the last post / page without a full reload required

## What I Need
What I need it to do

**Comment by Sjmarf** [comment] 2024-10-26 15:42
Duplicate of #174

**Closed by Sjmarf** 2024-10-26 15:42 UTC
Labels: enhancement
