### ISSUE TITLE
User Labels

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1299] opened 2024-09-05 15:23 UTC
Needs a more robust persistence system. We'll need such a system to handle a bunch of multi-account complexities anyway, so we can bolt this feature on once we have it in place.

**Comment by Sjmarf** [comment] 2024-09-05 16:23
Possible clone of #1085?

Requires #1133

**Comment by ghost** [comment] 2024-09-05 17:44
Also it would be nice for the app to show a list of users with their tags beside them so that anyone could export for desktop use too.

**Comment by Sjmarf** [comment] 2024-09-05 19:52
Yeah, that's a good idea.

Closing as duplicate of #1085

**Closed as not planned by Sjmarf** 2024-09-05 19:52 UTC
