### ISSUE TITLE
Tap comment reply in Inbox to go directly to the reply

### ISSUE THREAD

**Issue by einsteinx2** [mlemgroup/mlem#482] opened 2023-08-11 11:40 UTC
## Introduction
Currently it's possible to tap the link to the post or the reply text itself, which takes you to the top, but doesn't show you your comment. Tapping the text area of the comment should take you to your comment.

## Requirements
Add tap handler to the comment text box (or adjust existing one), have it open the post, then jump directly to your comment

## Discussion
Somewhat related to https://github.com/mlemgroup/mlem/issues/481

## What I Need
I'd like to be able to view the comment reply directly, currently it's necessary to manually scroll down and find it

**Comment by fer0n** [comment] 2023-08-11 16:12
Duplicate of #260 and child of #183

**Comment by einsteinx2** [comment] 2023-08-11 17:51
Whoops I had tried searching and somehow missed the dupes on both of these issues!

**Closed** 2023-08-15 18:48 UTC
Labels: enhancement
