### ISSUE TITLE
Allow a way to start a DM with other users.

### ISSUE THREAD

**Issue by ghost** [mlemgroup/mlem#1527] opened 2024-12-22 01:42 UTC
## Introduction
Unless I'm missing something there's no way to initiate a DM with other users only reply to one.

## Requirements
Provide a way to initiate a DM with other users from within in the app.

## Discussion
Perhaps this could be done from a user's profile.

## What I Need
Allow a way to initiate DMs with another user.

**Comment by Sjmarf** [comment] 2024-12-22 09:31
I'm working on this :) 

Duplicate of #622

**Closed as not planned** 2024-12-22 09:31 UTC

**Comment by ghost** [comment] 2024-12-23 20:58
Thank you!

I did search DM, but I guess he called it a message and not a DM, whoops.
