### ISSUE TITLE
Support widget

### ISSUE THREAD

**Issue by dtantono** [mlemgroup/mlem#148] opened 2023-06-14 13:58 UTC
## Introduction
Good iOS app such as Apollo have widget feature to track latest feeds and I think on Lemmy it should posess similar traits

## Requirements
Widget on iOS screen

## Discussion
I think iOS widget is helpful to track latest feeds. What do you think?

**Comment by ShadowJonathan** [comment] 2023-07-03 09:59
Duplicate of #77

**Closed by ShadowJonathan** 2023-07-03 09:59 UTC
Labels: enhancement
