### ISSUE TITLE
Tap comment in Overview/Comments section of profile tab to go to the comment

### ISSUE THREAD

**Issue by einsteinx2** [mlemgroup/mlem#481] opened 2023-08-11 11:34 UTC
## Introduction
Currently it's possible to tap the link to the post, which takes you to the top, but doesn't show you your comment. Tapping the text area of the comment should take you to your comment.

## Requirements
Add tap handler to the comment text box, have it open the post, then jump directly to your comment

## Discussion
Alternatively, we could just change the post link to go right to the comment, since in the context of this page (comment history), that may be preferable, but I can see the value in having the current behavior stay and just add the new behavior when tapping the comment text itself.

## What I Need
I'd like to be able to view my comments in context, which currently isn't possible without tapping the post link then manually scrolling down to find my comment which can be very difficult when there are many.

**Comment by fer0n** [comment] 2023-08-11 16:13
Duplicate of #183

**Closed** 2023-08-26 19:49 UTC
Labels: enhancement
