### ISSUE TITLE
Anonymous Browsing

### ISSUE THREAD

**Issue by chrispomeroyhale** [mlemgroup/mlem#20] opened 2023-07-02 19:13 UTC
## Introduction
I would appreciate the ability to browse any Lemmy instance without yet belonging to one. I recognize this will impose limitations on, say, subscribing which requires an account due to how ActivityPub works.

Use cases:
1) As a user I want a frictionless way to see content when first downloading the app
2) As a user I want to explore communities and figure out which community I want to belong to
3) As a user I don't want to provide a 3rd party with my account credentials (until a better auth protocol is implemented)

## Requirements
1. Modify SavedAccount so that accessToken and username (and id?) are optional
2. Add a flow to AddSavedInstanceView UI for adding an instance without logging in
3. All Requests that take in an account and use an accessToken should have optional inits or throw
4. Update all usages of these requests so that they try/throw -- leveraging the existing error catching
5. Remove the accessToken requirement from UserView from GetPersonDetailsRequest so that profiles load
6. Remove "Subscribed Communities" from CommunityListView when not authenticated
7. Remove InboxView and ProfileView tabs when not authenticated
8. Ensure no-auth SavedAccount gets persisted between app launches
9. Remove the default Community feed to Subscribed
10. Disable reply UI

## Discussion
The requirements I outlined above would be the bare minimum to give anonymous users access to the current features

## What I Need
I have a quick-and-dirty draft of this work which I am happy to contribute.

https://github.com/mormaer/Mlem/assets/55423/4653383e-fa5e-43a5-9837-f5da26cc73e8

**Comment by ShadowJonathan** [comment] 2023-07-03 09:31
Duplicate of https://github.com/mlemgroup/mlem/issues/21

**Closed by ShadowJonathan** 2023-07-03 09:31 UTC
Labels: enhancement
