### ISSUE TITLE
Add a tiny bit more padding to the top of the bottom bar of posts

### ISSUE THREAD

**Issue by hugpeter** [mlemgroup/mlem#143] opened 2023-06-17 22:08 UTC
Hello, could we have just a tiny bit more padding to the top side of the bottom button bar of the post? 

When posts have a link I'm accidentally fat fingering the link instead of interacting with the buttons on the bottom bar. 

![image](https://github.com/buresdv/Mlem/assets/26207788/072ff03f-9321-41d0-889b-26441302832d)

**Comment by ShadowJonathan** [comment] 2023-07-03 15:42
Duplicate of #28

**Closed by ShadowJonathan** 2023-07-03 15:42 UTC
Labels: enhancement
