### ISSUE TITLE
Implement spoiler support 

### ISSUE THREAD

**Issue by phareous** [mlemgroup/mlem#249] opened 2023-07-09 19:48 UTC
## Introduction
Brief history

Implement spoiler tag support so that tags in this format are hidden until clicked on 

::: spoiler label
Hidden text
:::

![IMG_3551](https://github.com/mlemgroup/mlem/assets/1590943/5ee7ae7b-90b3-4e14-b020-d5106169a3e7)

## Requirements
What needs to be done?

## Discussion
Go more in depth about the proposal

## What I Need
What I need it to do

**Comment by EricBAndrews** [comment] 2023-07-16 00:54
Duplicate of #114

**Closed by EricBAndrews** 2023-07-16 00:54 UTC
Labels: enhancement
