### ISSUE TITLE
In Comments View, it’s not quite intuitive how to add a top-level comment. I have an idea for how to make it better.

### ISSUE THREAD

**Issue by 100000BC** [mlemgroup/mlem#243] opened 2023-07-08 23:47 UTC
Here is what it currently looks like: 
![image](https://github.com/mlemgroup/mlem/assets/67931296/57c7a009-4edf-4b91-89dd-d319f44bfe1b)
![image](https://github.com/mlemgroup/mlem/assets/67931296/ab29f981-c1da-41da-b712-2f8adccd7384)

## Discussion
Maybe it’s as simple as making the background behind the post lighter in dark mode and darker in light mode? That would help separate the post itself from the comments, so that they don’t blend together.

I will mock something up and post in the comments to this issue.

**Comment by EricBAndrews** [comment] 2023-07-09 19:30
Closing this as dupe of #68--we have plans to make the expanded post not just a feed post with a comments section, I'll add a comment under that issue to make sure the delineation is nice and clear. Thanks for the feedback!

**Closed by EricBAndrews** 2023-07-09 19:30 UTC
