### ISSUE TITLE
Feature request: tapping the current tab again should scroll to top

### ISSUE THREAD

**Issue by antoinelibert** [mlemgroup/mlem#498] opened 2023-08-13 15:22 UTC
Hello,

It would be a great accessibility feature to be able to tap the current tab again and do a scroll to top. This would work for the "Feeds", "Inbox" and "Search" tab.

Thanks.

**Comment by EricBAndrews** [comment] 2023-08-13 15:24
Closing as duplicate of #60, should be out in the next build

**Closed** 2023-08-13 15:24 UTC
Labels: enhancement
