### ISSUE TITLE
Forces my volume to be on when app first opens* 

### ISSUE THREAD

**Issue by capybeby** [mlemgroup/mlem#660] opened 2023-09-28 01:05 UTC
**Describe the bug**
When I first open the app, my volume turns on one tick and I am unable to turn it off completely. It only happens the first time I open the app -- once I put it in the background, the volume automatically goes back to zero and I can bring the app back up and the volume will not change.

https://github.com/mlemgroup/mlem/assets/137654063/d1947464-244c-467d-a819-af2a2ddef797

**Expected Behavior**
For this not to happen.

**To Reproduce**
I open the app from fully closed.

**Mlem Information:**
V1.1, Build 697, test flight 

**Additional Context**
???????? Is all I've got really. Super weird, but maybe it's a me problem. This problem occurred before the IOS 17 update (I first noticed it August 16th according to an old screen recording) and has persisted after it.

**Comment by arader** [comment] 2023-10-02 04:36
this sounds like the same issue I’m seeing, #629  

I’m curious: when you’re in this state, if you adjust the volume, can you check the system settings and see if it’s actually changed the volume of your ringtone?

**Comment by Sjmarf** [comment] 2024-08-30 11:19
Duplicate of #629

**Closed** 2024-09-07 19:56 UTC
Labels: bug
