### ISSUE TITLE
Video Scrubbing

### ISSUE THREAD

**Issue by EricBAndrews** [mlemgroup/mlem#1491] opened 2024-12-09 17:52 UTC
Videos and animated media should be scrubbable. This is a little complicated since different formats are handled by different underlying views; #1490 introduces `.withAnimationControls`, which can serve as as generic UI element to put on top of custom per-type handlers.

**Comment by Sjmarf** [comment] 2024-12-17 15:27
Duplicate of #173

**Closed as not planned by Sjmarf** 2024-12-17 15:27 UTC
