### ISSUE TITLE
Make font size for post headlines in feed a fixed size

### ISSUE THREAD

**Issue by fer0n** [mlemgroup/mlem#438] opened 2023-08-06 10:58 UTC
**Describe the bug**
View a post in the feed with "large" post size where the first line is has a large font size.

**Expected Behavior**
Post headlines should all have the same fixed font (small) size in the feed with "large" post size

**Actual Behavior**
Headlines can be quite large, even parts that aren't large in the original post

![Post size example](https://github.com/mlemgroup/mlem/assets/20093825/2db1acb0-34f0-4339-96a2-1feb37be2760)

As you can see, in the post detail on the right only the first line is large. In the feed view on the left, everything has the same big font size. I'd argue that should be limited to one smaller size and is most likely not as it should be.

**To Reproduce**
- set post size to large
- find a post in the feed that has a headline in the first line followed by a different sized paragraph
- It will all have the same large font size as the headline

**Mlem Information:**
Mlem 1.0.1 (432)

**Additional Context**
Any other relevant information

**Comment by EricBAndrews** [comment] 2023-08-06 15:38
Dupe of #361

**Closed** 2023-08-06 15:39 UTC
Labels: bug
